export const seedData = {
    users: {
        _model: "User",
        homer: {
            firstName: "Homer",
            lastName: "Simpson",
            email: "homer@simpson.com",
            password: "secret",
        },
        marge: {
            firstName: "Marge",
            lastName: "Simpson",
            email: "marge@simpson.com",
            password: "secret",
        },
        bart: {
            firstName: "Bart",
            lastName: "Simpson",
            email: "bart@simpson.com",
            password: "secret",
        },
    },
    categories: {
        _model: "Category",
        category_1: {
            categoryName: "Anti Social Behavior",
        },
        category_2: {
            categoryName: "Domestic Crime",
        },
        category_3: {
            categoryName: "Hate Crime",
        },
        category_4: {
            categoryName: "Sexual Crime",
        },
        category_5: {
            categoryName: "Theft",
        },
        category_6: {
            categoryName: "Property Crime",
        },
        category_7: {
            categoryName: "Violent Event",
        },
    },
    reports: {
        _model: "Report",
        one: {
            reportName: "Scary Event",
            description: "Property Crime",
            reporter: "->users.bart",
            category: "->categories.category_5",
            lat: "52.161290",
            lng: "-7.51540",
            temperature: "4",
            code: "800",
            windSpeed: "1.34",
            pressure: "1080",
            windDirection: "102",
            timestamp: "5/15/2024, 11:06:28 AM",
            imageURL: "",
        },
        two: {
            reportName: "Night Event",
            description: "Property Crime",
            reporter: "->users.homer",
            category: "->categories.category_1",
            lat: "52.161290",
            lng: "-7.51540",
            temperature: "6",
            code: "200",
            windSpeed: "5",
            pressure: "1005",
            windDirection: "85",
            timestamp: "5/15/2024, 10:06:28 PM",
            imageURL: "https://res.cloudinary.com/dvynpodck/image/upload/v1716052368/dfpqgzrmmccl2hxvnjd2.svg",
        },
        three: {
            reportName: "Scary Event 2",
            description: "Very Scary Event Occurred",
            reporter: "->users.bart",
            category: "->categories.category_5",
            lat: "52.1",
            lng: "-7.5",
            temperature: "5",
            code: "200",
            windSpeed: "1.4",
            pressure: "1000",
            windDirection: "102",
            timestamp: "5/16/2024, 11:06:28 AM",
            imageURL: "",
        },
        four: {
            reportName: "Night Event in Malahide",
            description: "Very Scary Night Event",
            reporter: "->users.homer",
            category: "->categories.category_1",
            lat: "52.61290",
            lng: "-7.1540",
            temperature: "6",
            code: "200",
            windSpeed: "5",
            pressure: "1005",
            windDirection: "85",
            timestamp: "5/18/2024, 10:06:28 PM",
            imageURL: "https://res.cloudinary.com/dvynpodck/image/upload/v1716052368/dfpqgzrmmccl2hxvnjd2.svg",
        },
        five: {
            reportName: "Scary Event 2",
            description: "Very Scary Event Occurred 2",
            reporter: "->users.bart",
            category: "->categories.category_3",
            lat: "52.12361290",
            lng: "-7.51540",
            temperature: "4",
            code: "800",
            windSpeed: "1.34",
            pressure: "1080",
            windDirection: "102",
            timestamp: "5/20/2024, 11:06:28 AM",
            imageURL: "",
        },
        six: {
            reportName: "Night Event",
            description: "Very Scary Night Event",
            reporter: "->users.homer",
            category: "->categories.category_2",
            lat: "52.161290",
            lng: "-7.51540",
            temperature: "6",
            code: "200",
            windSpeed: "5",
            pressure: "1005",
            windDirection: "85",
            timestamp: "5/25/2024, 10:06:28 PM",
            imageURL: "https://res.cloudinary.com/dvynpodck/image/upload/v1716052368/dfpqgzrmmccl2hxvnjd2.svg",
        },
        seven: {
            reportName: "Scary Event",
            description: "Violent Event",
            reporter: "->users.bart",
            category: "->categories.category_6",
            lat: "52.161290",
            lng: "-7.51540",
            temperature: "4",
            code: "800",
            windSpeed: "1.34",
            pressure: "1080",
            windDirection: "102",
            timestamp: "5/25/2024, 11:06:28 AM",
            imageURL: "",
        },
        eight: {
            reportName: "Night Event",
            description: "Very Scary Night Event",
            reporter: "->users.homer",
            category: "->categories.category_1",
            lat: "52.161290",
            lng: "-7.51540",
            temperature: "6",
            code: "200",
            windSpeed: "5",
            pressure: "1005",
            windDirection: "85",
            timestamp: "5/15/2024, 10:06:28 PM",
            imageURL: "https://res.cloudinary.com/dvynpodck/image/upload/v1716052368/dfpqgzrmmccl2hxvnjd2.svg",
        },
        nine: {
            reportName: "Scary Event",
            description: "Very Scary Event Occurred",
            reporter: "->users.bart",
            category: "->categories.category_5",
            lat: "52.161290",
            lng: "-7.51540",
            temperature: "4",
            code: "800",
            windSpeed: "1.34",
            pressure: "1080",
            windDirection: "102",
            timestamp: "5/25/2024, 11:06:28 AM",
            imageURL: "",
        },
        ten: {
            reportName: "Night Event",
            description: "Very Scary Night Event",
            reporter: "->users.homer",
            category: "->categories.category_1",
            lat: "52.161290",
            lng: "-7.51540",
            temperature: "6",
            code: "200",
            windSpeed: "5",
            pressure: "1005",
            windDirection: "85",
            timestamp: "5/27/2024, 10:06:28 PM",
            imageURL: "https://res.cloudinary.com/dvynpodck/image/upload/v1716052368/dfpqgzrmmccl2hxvnjd2.svg",
        },
    },
};
